/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { GithubComSatstreamSsApiServerApiBlocksResponsesError } from '../models';
import { ResponsesGetAddressMempoolTxs } from '../models';
import { ResponsesGetMempoolTransactions } from '../models';
import { ResponsesGetMempoolTxInfo } from '../models';
/**
 * MempoolApi - axios parameter creator
 * @export
 */
export const MempoolApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get all mempool transactions for a specific address
         * @summary Get address mempool transactions
         * @param {string} address Bitcoin address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAddressMempoolTransactions: async (address: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'address' is not null or undefined
            if (address === null || address === undefined) {
                throw new RequiredError('address','Required parameter address was null or undefined when calling getAddressMempoolTransactions.');
            }
            const localVarPath = `/mempool/addresses/{address}/transactions`
                .replace(`{${"address"}}`, encodeURIComponent(String(address)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("X-API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["X-API-KEY"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get information about a specific transaction in the mempool
         * @summary Get mempool transaction info
         * @param {string} txid Transaction ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMempoolTransactionInfo: async (txid: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'txid' is not null or undefined
            if (txid === null || txid === undefined) {
                throw new RequiredError('txid','Required parameter txid was null or undefined when calling getMempoolTransactionInfo.');
            }
            const localVarPath = `/mempool/transactions/{txid}`
                .replace(`{${"txid"}}`, encodeURIComponent(String(txid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("X-API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["X-API-KEY"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all transactions currently in the mempool
         * @summary Get mempool transactions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMempoolTransactions: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/mempool/transactions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MempoolApi - functional programming interface
 * @export
 */
export const MempoolApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Get all mempool transactions for a specific address
         * @summary Get address mempool transactions
         * @param {string} address Bitcoin address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAddressMempoolTransactions(address: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ResponsesGetAddressMempoolTxs>>> {
            const localVarAxiosArgs = await MempoolApiAxiosParamCreator(configuration).getAddressMempoolTransactions(address, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get information about a specific transaction in the mempool
         * @summary Get mempool transaction info
         * @param {string} txid Transaction ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMempoolTransactionInfo(txid: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ResponsesGetMempoolTxInfo>>> {
            const localVarAxiosArgs = await MempoolApiAxiosParamCreator(configuration).getMempoolTransactionInfo(txid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get all transactions currently in the mempool
         * @summary Get mempool transactions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMempoolTransactions(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ResponsesGetMempoolTransactions>>> {
            const localVarAxiosArgs = await MempoolApiAxiosParamCreator(configuration).getMempoolTransactions(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MempoolApi - factory interface
 * @export
 */
export const MempoolApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Get all mempool transactions for a specific address
         * @summary Get address mempool transactions
         * @param {string} address Bitcoin address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAddressMempoolTransactions(address: string, options?: AxiosRequestConfig): Promise<AxiosResponse<ResponsesGetAddressMempoolTxs>> {
            return MempoolApiFp(configuration).getAddressMempoolTransactions(address, options).then((request) => request(axios, basePath));
        },
        /**
         * Get information about a specific transaction in the mempool
         * @summary Get mempool transaction info
         * @param {string} txid Transaction ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMempoolTransactionInfo(txid: string, options?: AxiosRequestConfig): Promise<AxiosResponse<ResponsesGetMempoolTxInfo>> {
            return MempoolApiFp(configuration).getMempoolTransactionInfo(txid, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all transactions currently in the mempool
         * @summary Get mempool transactions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMempoolTransactions(options?: AxiosRequestConfig): Promise<AxiosResponse<ResponsesGetMempoolTransactions>> {
            return MempoolApiFp(configuration).getMempoolTransactions(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MempoolApi - object-oriented interface
 * @export
 * @class MempoolApi
 * @extends {BaseAPI}
 */
export class MempoolApi extends BaseAPI {
    /**
     * Get all mempool transactions for a specific address
     * @summary Get address mempool transactions
     * @param {string} address Bitcoin address
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MempoolApi
     */
    public async getAddressMempoolTransactions(address: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<ResponsesGetAddressMempoolTxs>> {
        return MempoolApiFp(this.configuration).getAddressMempoolTransactions(address, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get information about a specific transaction in the mempool
     * @summary Get mempool transaction info
     * @param {string} txid Transaction ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MempoolApi
     */
    public async getMempoolTransactionInfo(txid: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<ResponsesGetMempoolTxInfo>> {
        return MempoolApiFp(this.configuration).getMempoolTransactionInfo(txid, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get all transactions currently in the mempool
     * @summary Get mempool transactions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MempoolApi
     */
    public async getMempoolTransactions(options?: AxiosRequestConfig) : Promise<AxiosResponse<ResponsesGetMempoolTransactions>> {
        return MempoolApiFp(this.configuration).getMempoolTransactions(options).then((request) => request(this.axios, this.basePath));
    }
}
