name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install Bun
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          version: 'latest'  # You can specify a specific version if needed

      # 3. Configure NPM for Scoped Package
      - name: Configure NPM for @hexmount scope
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          echo "@hexmount:registry=https://registry.npmjs.org/" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # 4. Install dependencies using Bun
      - name: Install dependencies
        run: bun install

      # 5. Build the project using Bun
      - name: Build
        run: bun run build

      # 6. Run tests using Bun
      - name: Run tests
        run: bun test

      # 7. Publish to NPM using Bun or NPM
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
