/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RunesBalance } from './runes-balance';
 /**
 * 
 *
 * @export
 * @interface AddressResponse
 */
export interface AddressResponse {

    /**
     * @type {Array<string>}
     * @memberof AddressResponse
     */
    inscriptions?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof AddressResponse
     */
    outputs?: Array<string>;

    /**
     * @type {Array<RunesBalance>}
     * @memberof AddressResponse
     */
    runesBalances?: Array<RunesBalance>;

    /**
     * @type {number}
     * @memberof AddressResponse
     */
    satBalance?: number;
}
