/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AddressRuneDelta
 */
export interface AddressRuneDelta {

    /**
     * @type {string}
     * @memberof AddressRuneDelta
     */
    address?: string;

    /**
     * @type {string}
     * @memberof AddressRuneDelta
     */
    amount?: string;

    /**
     * @type {number}
     * @memberof AddressRuneDelta
     */
    blockHeight?: number;

    /**
     * @type {string}
     * @memberof AddressRuneDelta
     */
    runeId?: string;

    /**
     * @type {string}
     * @memberof AddressRuneDelta
     */
    txid?: string;

    /**
     * @type {number}
     * @memberof AddressRuneDelta
     */
    vout?: number;
}
