/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BtcTx3 } from './btc-tx3';
 /**
 * 
 *
 * @export
 * @interface Block3
 */
export interface Block3 {

    /**
     * @type {string}
     * @memberof Block3
     */
    bits?: string;

    /**
     * @type {string}
     * @memberof Block3
     */
    chainwork?: string;

    /**
     * @type {number}
     * @memberof Block3
     */
    confirmations?: number;

    /**
     * @type {number}
     * @memberof Block3
     */
    difficulty?: number;

    /**
     * @type {string}
     * @memberof Block3
     */
    hash?: string;

    /**
     * @type {number}
     * @memberof Block3
     */
    height?: number;

    /**
     * @type {number}
     * @memberof Block3
     */
    mediantime?: number;

    /**
     * @type {string}
     * @memberof Block3
     */
    merkleroot?: string;

    /**
     * @type {number}
     * @memberof Block3
     */
    nTx?: number;

    /**
     * @type {string}
     * @memberof Block3
     */
    nextblockhash?: string;

    /**
     * @type {number}
     * @memberof Block3
     */
    nonce?: number;

    /**
     * @type {string}
     * @memberof Block3
     */
    previousblockhash?: string;

    /**
     * @type {number}
     * @memberof Block3
     */
    size?: number;

    /**
     * @type {number}
     * @memberof Block3
     */
    strippedsize?: number;

    /**
     * @type {number}
     * @memberof Block3
     */
    time?: number;

    /**
     * List of fully detailed transactions
     *
     * @type {Array<BtcTx3>}
     * @memberof Block3
     */
    tx?: Array<BtcTx3>;

    /**
     * @type {number}
     * @memberof Block3
     */
    version?: number;

    /**
     * @type {string}
     * @memberof Block3
     */
    versionHex?: string;

    /**
     * @type {number}
     * @memberof Block3
     */
    weight?: number;
}
