/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Transaction } from './transaction';
 /**
 * 
 *
 * @export
 * @interface BlockResponse
 */
export interface BlockResponse {

    /**
     * @type {number}
     * @memberof BlockResponse
     */
    bestHeight?: number;

    /**
     * @type {string}
     * @memberof BlockResponse
     */
    hash?: string;

    /**
     * @type {number}
     * @memberof BlockResponse
     */
    height?: number;

    /**
     * @type {Array<string>}
     * @memberof BlockResponse
     */
    inscriptions?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof BlockResponse
     */
    runes?: Array<string>;

    /**
     * @type {string}
     * @memberof BlockResponse
     */
    target?: string;

    /**
     * @type {Array<Transaction>}
     * @memberof BlockResponse
     */
    transactions?: Array<Transaction>;
}
