/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PrevOut } from './prev-out';
import { ScriptSig } from './script-sig';
 /**
 * 
 *
 * @export
 * @interface BlockVin3
 */
export interface BlockVin3 {

    /**
     * @type {string}
     * @memberof BlockVin3
     */
    coinbase?: string;

    /**
     * Detailed previous output
     *
     * @type {PrevOut}
     * @memberof BlockVin3
     */
    prevout?: PrevOut;

    /**
     * @type {ScriptSig}
     * @memberof BlockVin3
     */
    scriptSig?: ScriptSig;

    /**
     * @type {number}
     * @memberof BlockVin3
     */
    sequence?: number;

    /**
     * @type {string}
     * @memberof BlockVin3
     */
    txid?: string;

    /**
     * @type {Array<string>}
     * @memberof BlockVin3
     */
    txinwitness?: Array<string>;

    /**
     * @type {number}
     * @memberof BlockVin3
     */
    vout?: number;
}
