/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BlockVin3 } from './block-vin3';
import { Vout } from './vout';
 /**
 * 
 *
 * @export
 * @interface BtcTx3
 */
export interface BtcTx3 {

    /**
     * @type {number}
     * @memberof BtcTx3
     */
    fee?: number;

    /**
     * @type {string}
     * @memberof BtcTx3
     */
    hash?: string;

    /**
     * @type {string}
     * @memberof BtcTx3
     */
    hex?: string;

    /**
     * @type {number}
     * @memberof BtcTx3
     */
    locktime?: number;

    /**
     * @type {number}
     * @memberof BtcTx3
     */
    size?: number;

    /**
     * @type {string}
     * @memberof BtcTx3
     */
    txid?: string;

    /**
     * @type {number}
     * @memberof BtcTx3
     */
    version?: number;

    /**
     * @type {Array<BlockVin3>}
     * @memberof BtcTx3
     */
    vin?: Array<BlockVin3>;

    /**
     * @type {Array<Vout>}
     * @memberof BtcTx3
     */
    vout?: Array<Vout>;

    /**
     * @type {number}
     * @memberof BtcTx3
     */
    vsize?: number;

    /**
     * @type {number}
     * @memberof BtcTx3
     */
    weight?: number;
}
