/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ChainTxStats
 */
export interface ChainTxStats {

    /**
     * The timestamp for the final block in the window
     *
     * @type {number}
     * @memberof ChainTxStats
     */
    time?: number;

    /**
     * The total number of transactions in the chain
     *
     * @type {number}
     * @memberof ChainTxStats
     */
    txcount?: number;

    /**
     * The average rate of transactions per second
     *
     * @type {number}
     * @memberof ChainTxStats
     */
    txrate?: number;

    /**
     * Size of the window in number of blocks
     *
     * @type {number}
     * @memberof ChainTxStats
     */
    windowBlockCount?: number;

    /**
     * The hash of the final block in the window
     *
     * @type {string}
     * @memberof ChainTxStats
     */
    windowFinalBlockHash?: string;

    /**
     * The height of the final block in the window
     *
     * @type {number}
     * @memberof ChainTxStats
     */
    windowFinalBlockHeight?: number;

    /**
     * The elapsed time in the window in seconds
     *
     * @type {number}
     * @memberof ChainTxStats
     */
    windowInterval?: number;

    /**
     * The number of transactions in the window
     *
     * @type {number}
     * @memberof ChainTxStats
     */
    windowTxCount?: number;
}
