/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreatePSBTOutput
 */
export interface CreatePSBTOutput {

    /**
     * The bitcoin address to send to
     *
     * @type {string}
     * @memberof CreatePSBTOutput
     */
    address?: string;

    /**
     * The amount in BTC to send
     *
     * @type {number}
     * @memberof CreatePSBTOutput
     */
    amount?: number;

    /**
     * Hex-encoded data to embed in the transaction
     *
     * @type {string}
     * @memberof CreatePSBTOutput
     */
    data?: string;
}
