/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Bip32Deriv } from './bip32-deriv';
import { PSBTWitnessUtxo } from './psbtwitness-utxo';
import { RawTx1 } from './raw-tx1';
import { Script } from './script';
 /**
 * 
 *
 * @export
 * @interface DecodedPSBTInput
 */
export interface DecodedPSBTInput {

    /**
     * The BIP32 derivation paths
     *
     * @type {{ [key: string]: Bip32Deriv; }}
     * @memberof DecodedPSBTInput
     */
    bip32Derivs?: { [key: string]: Bip32Deriv; };

    /**
     * The final script sig
     *
     * @type {Script}
     * @memberof DecodedPSBTInput
     */
    finalScriptsig?: Script;

    /**
     * The final script witness
     *
     * @type {Array<string>}
     * @memberof DecodedPSBTInput
     */
    finalScriptwitness?: Array<string>;

    /**
     * Decoded network transaction for non-witness UTXOs
     *
     * @type {RawTx1}
     * @memberof DecodedPSBTInput
     */
    nonWitnessUtxo?: RawTx1;

    /**
     * The public key and signature pairs
     *
     * @type {{ [key: string]: string; }}
     * @memberof DecodedPSBTInput
     */
    partialSignatures?: { [key: string]: string; };

    /**
     * The redeem script
     *
     * @type {Script}
     * @memberof DecodedPSBTInput
     */
    redeemScript?: Script;

    /**
     * The sighash type to be used
     *
     * @type {string}
     * @memberof DecodedPSBTInput
     */
    sighash?: string;

    /**
     * Unknown fields
     *
     * @type {{ [key: string]: any; }}
     * @memberof DecodedPSBTInput
     */
    unknown?: { [key: string]: any; };

    /**
     * The witness script
     *
     * @type {Script}
     * @memberof DecodedPSBTInput
     */
    witnessScript?: Script;

    /**
     * Transaction output for witness UTXOs
     *
     * @type {PSBTWitnessUtxo}
     * @memberof DecodedPSBTInput
     */
    witnessUtxo?: PSBTWitnessUtxo;
}
