/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DecodedInscription } from './decoded-inscription';
import { RunestoneData } from './runestone-data';
 /**
 * 
 *
 * @export
 * @interface DecodeResponse
 */
export interface DecodeResponse {

    /**
     * @type {Array<DecodedInscription>}
     * @memberof DecodeResponse
     */
    inscriptions?: Array<DecodedInscription>;

    /**
     * @type {RunestoneData}
     * @memberof DecodeResponse
     */
    runestone?: RunestoneData;
}
