/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Block3 } from './block3';
 /**
 * 
 *
 * @export
 * @interface GetBlockPrevoutResponse
 */
export interface GetBlockPrevoutResponse {

    /**
     * @type {number}
     * @memberof GetBlockPrevoutResponse
     */
    code?: number;

    /**
     * @type {Block3}
     * @memberof GetBlockPrevoutResponse
     */
    data?: Block3;

    /**
     * @type {string}
     * @memberof GetBlockPrevoutResponse
     */
    msg?: string;
}
