/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BlockResponse } from './block-response';
 /**
 * 
 *
 * @export
 * @interface GetBlockResponse
 */
export interface GetBlockResponse {

    /**
     * @type {number}
     * @memberof GetBlockResponse
     */
    code?: number;

    /**
     * @type {BlockResponse}
     * @memberof GetBlockResponse
     */
    data?: BlockResponse;

    /**
     * @type {string}
     * @memberof GetBlockResponse
     */
    msg?: string;
}
