/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { StatusResponse } from './status-response';
 /**
 * 
 *
 * @export
 * @interface GetStatusResponse
 */
export interface GetStatusResponse {

    /**
     * @type {number}
     * @memberof GetStatusResponse
     */
    code?: number;

    /**
     * @type {StatusResponse}
     * @memberof GetStatusResponse
     */
    data?: StatusResponse;

    /**
     * @type {string}
     * @memberof GetStatusResponse
     */
    msg?: string;
}
