/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AddressRuneDelta } from './address-rune-delta';
 /**
 * 
 *
 * @export
 * @interface GetAddressRuneDeltasResponse
 */
export interface GetAddressRuneDeltasResponse {

    /**
     * @type {number}
     * @memberof GetAddressRuneDeltasResponse
     */
    code?: number;

    /**
     * @type {Array<AddressRuneDelta>}
     * @memberof GetAddressRuneDeltasResponse
     */
    data?: Array<AddressRuneDelta>;

    /**
     * @type {boolean}
     * @memberof GetAddressRuneDeltasResponse
     */
    hasMore?: boolean;

    /**
     * @type {string}
     * @memberof GetAddressRuneDeltasResponse
     */
    msg?: string;
}
