/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RuneResponse } from './rune-response';
 /**
 * 
 *
 * @export
 * @interface GetRuneResponse
 */
export interface GetRuneResponse {

    /**
     * @type {number}
     * @memberof GetRuneResponse
     */
    code?: number;

    /**
     * @type {RuneResponse}
     * @memberof GetRuneResponse
     */
    data?: RuneResponse;

    /**
     * @type {string}
     * @memberof GetRuneResponse
     */
    msg?: string;
}
