/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MempoolAncestorsData } from './mempool-ancestors-data';
 /**
 * 
 *
 * @export
 * @interface GetMempoolAncestorsResponse
 */
export interface GetMempoolAncestorsResponse {

    /**
     * @type {number}
     * @memberof GetMempoolAncestorsResponse
     */
    code?: number;

    /**
     * @type {MempoolAncestorsData}
     * @memberof GetMempoolAncestorsResponse
     */
    data?: MempoolAncestorsData;

    /**
     * @type {string}
     * @memberof GetMempoolAncestorsResponse
     */
    msg?: string;
}
