/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GetAddressBalanceResponseData } from './get-address-balance-response-data';
 /**
 * 
 *
 * @export
 * @interface GetAddressBalanceResponse
 */
export interface GetAddressBalanceResponse {

    /**
     * @type {number}
     * @memberof GetAddressBalanceResponse
     */
    code?: number;

    /**
     * @type {GetAddressBalanceResponseData}
     * @memberof GetAddressBalanceResponse
     */
    data?: GetAddressBalanceResponseData;

    /**
     * @type {string}
     * @memberof GetAddressBalanceResponse
     */
    msg?: string;
}
