/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetAddressBalanceResponseData
 */
export interface GetAddressBalanceResponseData {

    /**
     * @type {string}
     * @memberof GetAddressBalanceResponseData
     */
    address?: string;

    /**
     * @type {number}
     * @memberof GetAddressBalanceResponseData
     */
    balance?: number;
}
