/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Block2 } from './block2';
 /**
 * 
 *
 * @export
 * @interface GetBlockDecodedResponse
 */
export interface GetBlockDecodedResponse {

    /**
     * @type {number}
     * @memberof GetBlockDecodedResponse
     */
    code?: number;

    /**
     * @type {Block2}
     * @memberof GetBlockDecodedResponse
     */
    data?: Block2;

    /**
     * @type {string}
     * @memberof GetBlockDecodedResponse
     */
    msg?: string;
}
