/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetMempoolAncestorsRequest
 */
export interface GetMempoolAncestorsRequest {

    /**
     * Required: The transaction id (must be in mempool)
     *
     * @type {string}
     * @memberof GetMempoolAncestorsRequest
     */
    txid?: string;

    /**
     * Optional: True for detailed information, false for just txids
     *
     * @type {boolean}
     * @memberof GetMempoolAncestorsRequest
     */
    verbose?: boolean;
}
