/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BlockStats } from './block-stats';
 /**
 * 
 *
 * @export
 * @interface GetBlockStatsResponse
 */
export interface GetBlockStatsResponse {

    /**
     * @type {number}
     * @memberof GetBlockStatsResponse
     */
    code?: number;

    /**
     * @type {BlockStats}
     * @memberof GetBlockStatsResponse
     */
    data?: BlockStats;

    /**
     * @type {string}
     * @memberof GetBlockStatsResponse
     */
    msg?: string;
}
