/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { LatestInscriptionsResponse } from './latest-inscriptions-response';
 /**
 * 
 *
 * @export
 * @interface GetLatestInscriptionsResponse
 */
export interface GetLatestInscriptionsResponse {

    /**
     * @type {number}
     * @memberof GetLatestInscriptionsResponse
     */
    code?: number;

    /**
     * @type {LatestInscriptionsResponse}
     * @memberof GetLatestInscriptionsResponse
     */
    data?: LatestInscriptionsResponse;

    /**
     * @type {string}
     * @memberof GetLatestInscriptionsResponse
     */
    msg?: string;
}
