/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsDatabaseAddressDelta } from './github-com-satstream-ss-utils-database-address-delta';
 /**
 * 
 *
 * @export
 * @interface GetAddressDeltasResponse
 */
export interface GetAddressDeltasResponse {

    /**
     * @type {number}
     * @memberof GetAddressDeltasResponse
     */
    code?: number;

    /**
     * @type {Array<GithubComSatstreamSsUtilsDatabaseAddressDelta>}
     * @memberof GetAddressDeltasResponse
     */
    data?: Array<GithubComSatstreamSsUtilsDatabaseAddressDelta>;

    /**
     * @type {string}
     * @memberof GetAddressDeltasResponse
     */
    msg?: string;
}
