/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetRawMempoolRequest
 */
export interface GetRawMempoolRequest {

    /**
     * Optional: Returns txids with mempool sequence number
     *
     * @type {boolean}
     * @memberof GetRawMempoolRequest
     */
    mempoolSequence?: boolean;
}
