/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsBitcoinCliBlockVin2 } from './github-com-satstream-ss-utils-bitcoin-cli-block-vin2';
import { GithubComSatstreamSsUtilsBitcoinCliVout } from './github-com-satstream-ss-utils-bitcoin-cli-vout';
 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsUtilsBitcoinCliBtcTx2
 */
export interface GithubComSatstreamSsUtilsBitcoinCliBtcTx2 {

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliBtcTx2
     */
    fee?: number;

    /**
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliBtcTx2
     */
    hash?: string;

    /**
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliBtcTx2
     */
    hex?: string;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliBtcTx2
     */
    locktime?: number;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliBtcTx2
     */
    size?: number;

    /**
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliBtcTx2
     */
    txid?: string;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliBtcTx2
     */
    version?: number;

    /**
     * @type {Array<GithubComSatstreamSsUtilsBitcoinCliBlockVin2>}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliBtcTx2
     */
    vin?: Array<GithubComSatstreamSsUtilsBitcoinCliBlockVin2>;

    /**
     * @type {Array<GithubComSatstreamSsUtilsBitcoinCliVout>}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliBtcTx2
     */
    vout?: Array<GithubComSatstreamSsUtilsBitcoinCliVout>;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliBtcTx2
     */
    vsize?: number;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliBtcTx2
     */
    weight?: number;
}
