/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsUtilsBitcoinCliUTXOUnspendables
 */
export interface GithubComSatstreamSsUtilsBitcoinCliUTXOUnspendables {

    /**
     * Transactions overridden by duplicates
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliUTXOUnspendables
     */
    bip30?: number;

    /**
     * Unspendable amount of Genesis block subsidy
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliUTXOUnspendables
     */
    genesisBlock?: number;

    /**
     * Amounts sent to unspendable scripts
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliUTXOUnspendables
     */
    scripts?: number;

    /**
     * Fee rewards unclaimed by miners
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliUTXOUnspendables
     */
    unclaimedRewards?: number;
}
