/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsUtilsBitcoinCliScript
 */
export interface GithubComSatstreamSsUtilsBitcoinCliScript {

    /**
     * The Bitcoin address (if there is one)
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliScript
     */
    address?: string;

    /**
     * The assembly representation of the script
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliScript
     */
    asm?: string;

    /**
     * The hex representation of the script
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliScript
     */
    hex?: string;

    /**
     * The type of the script (e.g., 'pubkeyhash')
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliScript
     */
    type?: string;
}
