/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTInput } from './github-com-satstream-ss-api-server-api-transaction-requests-create-psbtinput';
import { GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTOutput } from './github-com-satstream-ss-api-server-api-transaction-requests-create-psbtoutput';
 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTRequest
 */
export interface GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTRequest {

    /**
     * The inputs for the transaction
     *
     * @type {Array<GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTInput>}
     * @memberof GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTRequest
     */
    inputs: Array<GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTInput>;

    /**
     * Raw locktime. Non-0 value also locktime-activates inputs Optional, defaults to 0
     *
     * @type {number}
     * @memberof GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTRequest
     */
    locktime?: number;

    /**
     * The outputs for the transaction Each address can only appear once and there can only be one 'data' object
     *
     * @type {Array<GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTOutput>}
     * @memberof GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTRequest
     */
    outputs: Array<GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTOutput>;

    /**
     * Marks this transaction as BIP125-replaceable Allows this transaction to be replaced by a transaction with higher fees If provided, it is an error if explicit sequence numbers are incompatible Optional, defaults to true
     *
     * @type {boolean}
     * @memberof GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTRequest
     */
    replaceable?: boolean;
}
