/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsBitcoinCliScriptPubKey } from './github-com-satstream-ss-utils-bitcoin-cli-script-pub-key';
 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsUtilsBitcoinCliPrevOut
 */
export interface GithubComSatstreamSsUtilsBitcoinCliPrevOut {

    /**
     * @type {boolean}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliPrevOut
     */
    generated?: boolean;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliPrevOut
     */
    height?: number;

    /**
     * @type {GithubComSatstreamSsUtilsBitcoinCliScriptPubKey}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliPrevOut
     */
    scriptPubKey?: GithubComSatstreamSsUtilsBitcoinCliScriptPubKey;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliPrevOut
     */
    value?: number;
}
