/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsUtilsOrdServerResponsesDuration
 */
export interface GithubComSatstreamSsUtilsOrdServerResponsesDuration {

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesDuration
     */
    nanos?: number;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesDuration
     */
    secs?: number;
}
