/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsOrdServerResponsesAddressResponse } from './github-com-satstream-ss-utils-ord-server-responses-address-response';
 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsApiServerApiAddressResponsesAddressResponse
 */
export interface GithubComSatstreamSsApiServerApiAddressResponsesAddressResponse {

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsApiServerApiAddressResponsesAddressResponse
     */
    code?: number;

    /**
     * @type {GithubComSatstreamSsUtilsOrdServerResponsesAddressResponse}
     * @memberof GithubComSatstreamSsApiServerApiAddressResponsesAddressResponse
     */
    data?: GithubComSatstreamSsUtilsOrdServerResponsesAddressResponse;

    /**
     * @type {string}
     * @memberof GithubComSatstreamSsApiServerApiAddressResponsesAddressResponse
     */
    msg?: string;
}
