/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsRpcPrevOut } from './github-com-satstream-ss-utils-rpc-prev-out';
import { GithubComSatstreamSsUtilsRpcScriptSig } from './github-com-satstream-ss-utils-rpc-script-sig';
 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsUtilsRpcVin
 */
export interface GithubComSatstreamSsUtilsRpcVin {

    /**
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsRpcVin
     */
    coinbase?: string;

    /**
     * @type {GithubComSatstreamSsUtilsRpcPrevOut}
     * @memberof GithubComSatstreamSsUtilsRpcVin
     */
    prevout?: GithubComSatstreamSsUtilsRpcPrevOut;

    /**
     * @type {GithubComSatstreamSsUtilsRpcScriptSig}
     * @memberof GithubComSatstreamSsUtilsRpcVin
     */
    scriptSig?: GithubComSatstreamSsUtilsRpcScriptSig;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsRpcVin
     */
    sequence?: number;

    /**
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsRpcVin
     */
    txid?: string;

    /**
     * @type {Array<string>}
     * @memberof GithubComSatstreamSsUtilsRpcVin
     */
    txinwitness?: Array<string>;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsRpcVin
     */
    vout?: number;
}
