/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsUtilsBitcoinCliSegwitDetails
 */
export interface GithubComSatstreamSsUtilsBitcoinCliSegwitDetails {

    /**
     * The Bitcoin address (only if well-defined)
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliSegwitDetails
     */
    address?: string;

    /**
     * String representation of the script public key
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliSegwitDetails
     */
    asm?: string;

    /**
     * Inferred descriptor for the script
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliSegwitDetails
     */
    desc?: string;

    /**
     * Hex string of the script public key
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliSegwitDetails
     */
    hex?: string;

    /**
     * P2SH address wrapping this witness script
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliSegwitDetails
     */
    p2shSegwit?: string;

    /**
     * The type of the script public key
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliSegwitDetails
     */
    type?: string;
}
