/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsBitcoinCliUTXOBlockInfo } from './github-com-satstream-ss-utils-bitcoin-cli-utxoblock-info';
 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsUtilsBitcoinCliUTXOSetInfo
 */
export interface GithubComSatstreamSsUtilsBitcoinCliUTXOSetInfo {

    /**
     * The hash of the block at which these statistics are calculated
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliUTXOSetInfo
     */
    bestblock?: string;

    /**
     * Info on amounts in the block at this height
     *
     * @type {GithubComSatstreamSsUtilsBitcoinCliUTXOBlockInfo}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliUTXOSetInfo
     */
    blockInfo?: GithubComSatstreamSsUtilsBitcoinCliUTXOBlockInfo;

    /**
     * Database-independent metric indicating the UTXO set size
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliUTXOSetInfo
     */
    bogosize?: number;

    /**
     * The estimated size of the chainstate on disk
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliUTXOSetInfo
     */
    diskSize?: number;

    /**
     * The serialized hash (only for hash_serialized_2)
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliUTXOSetInfo
     */
    hashSerialized2?: string;

    /**
     * The block height of the returned statistics
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliUTXOSetInfo
     */
    height?: number;

    /**
     * The serialized hash (only for muhash)
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliUTXOSetInfo
     */
    muhash?: string;

    /**
     * The total amount of coins in the UTXO set
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliUTXOSetInfo
     */
    totalAmount?: number;

    /**
     * Total amount permanently excluded from UTXO set
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliUTXOSetInfo
     */
    totalUnspendableAmount?: number;

    /**
     * The number of transactions with unspent outputs
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliUTXOSetInfo
     */
    transactions?: number;

    /**
     * The number of unspent transaction outputs
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliUTXOSetInfo
     */
    txouts?: number;
}
