/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsOrdServerResponsesBlockResponse } from './github-com-satstream-ss-utils-ord-server-responses-block-response';
 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsApiServerApiBlockResponsesBlockResponse
 */
export interface GithubComSatstreamSsApiServerApiBlockResponsesBlockResponse {

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsApiServerApiBlockResponsesBlockResponse
     */
    code?: number;

    /**
     * @type {GithubComSatstreamSsUtilsOrdServerResponsesBlockResponse}
     * @memberof GithubComSatstreamSsApiServerApiBlockResponsesBlockResponse
     */
    data?: GithubComSatstreamSsUtilsOrdServerResponsesBlockResponse;

    /**
     * @type {string}
     * @memberof GithubComSatstreamSsApiServerApiBlockResponsesBlockResponse
     */
    msg?: string;
}
