/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsBitcoinCliScriptPubKey } from './github-com-satstream-ss-utils-bitcoin-cli-script-pub-key';
 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsUtilsBitcoinCliTxOut
 */
export interface GithubComSatstreamSsUtilsBitcoinCliTxOut {

    /**
     * The hash of the block at the tip of the chain
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliTxOut
     */
    bestblock?: string;

    /**
     * Whether this is a coinbase transaction
     *
     * @type {boolean}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliTxOut
     */
    coinbase?: boolean;

    /**
     * The number of confirmations
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliTxOut
     */
    confirmations?: number;

    /**
     * The public key script
     *
     * @type {GithubComSatstreamSsUtilsBitcoinCliScriptPubKey}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliTxOut
     */
    scriptPubKey?: GithubComSatstreamSsUtilsBitcoinCliScriptPubKey;

    /**
     * The transaction value in BTC
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliTxOut
     */
    value?: number;
}
