/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsOrdServerResponsesRuneTerms } from './github-com-satstream-ss-utils-ord-server-responses-rune-terms';
 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsUtilsOrdServerResponsesRuneEntry
 */
export interface GithubComSatstreamSsUtilsOrdServerResponsesRuneEntry {

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesRuneEntry
     */
    block?: number;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesRuneEntry
     */
    burned?: number;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesRuneEntry
     */
    divisibility?: number;

    /**
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesRuneEntry
     */
    etching?: string;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesRuneEntry
     */
    mints?: number;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesRuneEntry
     */
    number?: number;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesRuneEntry
     */
    premine?: number;

    /**
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesRuneEntry
     */
    spacedRune?: string;

    /**
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesRuneEntry
     */
    symbol?: string;

    /**
     * @type {GithubComSatstreamSsUtilsOrdServerResponsesRuneTerms}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesRuneEntry
     */
    terms?: GithubComSatstreamSsUtilsOrdServerResponsesRuneTerms;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesRuneEntry
     */
    timestamp?: number;

    /**
     * @type {boolean}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesRuneEntry
     */
    turbo?: boolean;
}
