/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsBitcoinCliScript } from './github-com-satstream-ss-utils-bitcoin-cli-script';
 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsUtilsBitcoinCliPSBTWitnessUtxo
 */
export interface GithubComSatstreamSsUtilsBitcoinCliPSBTWitnessUtxo {

    /**
     * The value in BTC
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliPSBTWitnessUtxo
     */
    amount?: number;

    /**
     * The script pub key
     *
     * @type {GithubComSatstreamSsUtilsBitcoinCliScript}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliPSBTWitnessUtxo
     */
    scriptPubKey?: GithubComSatstreamSsUtilsBitcoinCliScript;
}
