/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsBitcoinCliPrevOut } from './github-com-satstream-ss-utils-bitcoin-cli-prev-out';
import { GithubComSatstreamSsUtilsBitcoinCliScriptSig } from './github-com-satstream-ss-utils-bitcoin-cli-script-sig';
 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsUtilsBitcoinCliTxVin2
 */
export interface GithubComSatstreamSsUtilsBitcoinCliTxVin2 {

    /**
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliTxVin2
     */
    coinbase?: string;

    /**
     * @type {GithubComSatstreamSsUtilsBitcoinCliPrevOut}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliTxVin2
     */
    prevout?: GithubComSatstreamSsUtilsBitcoinCliPrevOut;

    /**
     * @type {GithubComSatstreamSsUtilsBitcoinCliScriptSig}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliTxVin2
     */
    scriptSig?: GithubComSatstreamSsUtilsBitcoinCliScriptSig;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliTxVin2
     */
    sequence?: number;

    /**
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliTxVin2
     */
    txid?: string;

    /**
     * @type {Array<string>}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliTxVin2
     */
    txinwitness?: Array<string>;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliTxVin2
     */
    vout?: number;
}
