/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsUtilsBitcoinCliPSBTMissingData
 */
export interface GithubComSatstreamSsUtilsBitcoinCliPSBTMissingData {

    /**
     * @type {Array<string>}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliPSBTMissingData
     */
    pubkeys?: Array<string>;

    /**
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliPSBTMissingData
     */
    redeemscript?: string;

    /**
     * @type {Array<string>}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliPSBTMissingData
     */
    signatures?: Array<string>;

    /**
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliPSBTMissingData
     */
    witnessscript?: string;
}
