/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsOrdServerResponsesInscriptionData } from './github-com-satstream-ss-utils-ord-server-responses-inscription-data';
 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsUtilsOrdServerResponsesDecodedInscription
 */
export interface GithubComSatstreamSsUtilsOrdServerResponsesDecodedInscription {

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesDecodedInscription
     */
    input?: number;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesDecodedInscription
     */
    offset?: number;

    /**
     * @type {GithubComSatstreamSsUtilsOrdServerResponsesInscriptionData}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesDecodedInscription
     */
    payload?: GithubComSatstreamSsUtilsOrdServerResponsesInscriptionData;

    /**
     * @type {boolean}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesDecodedInscription
     */
    pushnum?: boolean;

    /**
     * @type {boolean}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesDecodedInscription
     */
    stutter?: boolean;
}
