/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsOrdServerResponsesLatestInscriptionsResponse } from './github-com-satstream-ss-utils-ord-server-responses-latest-inscriptions-response';
 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsApiServerApiInscriptionResponsesLatestInscriptionsResponse
 */
export interface GithubComSatstreamSsApiServerApiInscriptionResponsesLatestInscriptionsResponse {

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsApiServerApiInscriptionResponsesLatestInscriptionsResponse
     */
    code?: number;

    /**
     * @type {GithubComSatstreamSsUtilsOrdServerResponsesLatestInscriptionsResponse}
     * @memberof GithubComSatstreamSsApiServerApiInscriptionResponsesLatestInscriptionsResponse
     */
    data?: GithubComSatstreamSsUtilsOrdServerResponsesLatestInscriptionsResponse;

    /**
     * @type {string}
     * @memberof GithubComSatstreamSsApiServerApiInscriptionResponsesLatestInscriptionsResponse
     */
    msg?: string;
}
