/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsUtilsBitcoinCliMiningInfo
 */
export interface GithubComSatstreamSsUtilsBitcoinCliMiningInfo {

    /**
     * The current block
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliMiningInfo
     */
    blocks?: number;

    /**
     * Current network name
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliMiningInfo
     */
    chain?: string;

    /**
     * The number of block transactions of the last assembled block
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliMiningInfo
     */
    currentblocktx?: number;

    /**
     * The block weight of the last assembled block
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliMiningInfo
     */
    currentblockweight?: number;

    /**
     * The current difficulty
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliMiningInfo
     */
    difficulty?: number;

    /**
     * The network hashes per second
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliMiningInfo
     */
    networkhashps?: number;

    /**
     * The size of the mempool
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliMiningInfo
     */
    pooledtx?: number;

    /**
     * Any network and blockchain warnings
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliMiningInfo
     */
    warnings?: string;
}
