/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsOrdServerResponsesSatoshiResponse } from './github-com-satstream-ss-utils-ord-server-responses-satoshi-response';
 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsApiServerApiSatoshiResponsesSatoshiResponse
 */
export interface GithubComSatstreamSsApiServerApiSatoshiResponsesSatoshiResponse {

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsApiServerApiSatoshiResponsesSatoshiResponse
     */
    code?: number;

    /**
     * @type {GithubComSatstreamSsUtilsOrdServerResponsesSatoshiResponse}
     * @memberof GithubComSatstreamSsApiServerApiSatoshiResponsesSatoshiResponse
     */
    data?: GithubComSatstreamSsUtilsOrdServerResponsesSatoshiResponse;

    /**
     * @type {string}
     * @memberof GithubComSatstreamSsApiServerApiSatoshiResponsesSatoshiResponse
     */
    msg?: string;
}
