/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsOrdServerResponsesInput } from './github-com-satstream-ss-utils-ord-server-responses-input';
import { GithubComSatstreamSsUtilsOrdServerResponsesOutput } from './github-com-satstream-ss-utils-ord-server-responses-output';
 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsUtilsOrdServerResponsesTransaction
 */
export interface GithubComSatstreamSsUtilsOrdServerResponsesTransaction {

    /**
     * @type {Array<GithubComSatstreamSsUtilsOrdServerResponsesInput>}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesTransaction
     */
    input?: Array<GithubComSatstreamSsUtilsOrdServerResponsesInput>;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesTransaction
     */
    lockTime?: number;

    /**
     * @type {Array<GithubComSatstreamSsUtilsOrdServerResponsesOutput>}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesTransaction
     */
    output?: Array<GithubComSatstreamSsUtilsOrdServerResponsesOutput>;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsOrdServerResponsesTransaction
     */
    version?: number;
}
