/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsApiServerApiPsbtRequestsCreatePSBTInput } from './github-com-satstream-ss-api-server-api-psbt-requests-create-psbtinput';
import { GithubComSatstreamSsApiServerApiPsbtRequestsCreatePSBTOutput } from './github-com-satstream-ss-api-server-api-psbt-requests-create-psbtoutput';
 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsApiServerApiPsbtRequestsCreatePSBTRequest
 */
export interface GithubComSatstreamSsApiServerApiPsbtRequestsCreatePSBTRequest {

    /**
     * @type {Array<GithubComSatstreamSsApiServerApiPsbtRequestsCreatePSBTInput>}
     * @memberof GithubComSatstreamSsApiServerApiPsbtRequestsCreatePSBTRequest
     */
    inputs: Array<GithubComSatstreamSsApiServerApiPsbtRequestsCreatePSBTInput>;

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsApiServerApiPsbtRequestsCreatePSBTRequest
     */
    locktime?: number;

    /**
     * @type {Array<GithubComSatstreamSsApiServerApiPsbtRequestsCreatePSBTOutput>}
     * @memberof GithubComSatstreamSsApiServerApiPsbtRequestsCreatePSBTRequest
     */
    outputs: Array<GithubComSatstreamSsApiServerApiPsbtRequestsCreatePSBTOutput>;

    /**
     * @type {boolean}
     * @memberof GithubComSatstreamSsApiServerApiPsbtRequestsCreatePSBTRequest
     */
    replaceable?: boolean;
}
