/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsOrdServerResponsesStatusResponse } from './github-com-satstream-ss-utils-ord-server-responses-status-response';
 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsApiServerApiStatusResponsesStatusResponse
 */
export interface GithubComSatstreamSsApiServerApiStatusResponsesStatusResponse {

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsApiServerApiStatusResponsesStatusResponse
     */
    code?: number;

    /**
     * @type {GithubComSatstreamSsUtilsOrdServerResponsesStatusResponse}
     * @memberof GithubComSatstreamSsApiServerApiStatusResponsesStatusResponse
     */
    data?: GithubComSatstreamSsUtilsOrdServerResponsesStatusResponse;

    /**
     * @type {string}
     * @memberof GithubComSatstreamSsApiServerApiStatusResponsesStatusResponse
     */
    msg?: string;
}
