/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTOutput
 */
export interface GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTOutput {

    /**
     * The bitcoin address and amount pairs Key is the bitcoin address, value is the amount in BTC
     *
     * @type {number}
     * @memberof GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTOutput
     */
    address?: number;

    /**
     * Hex-encoded data output If present, this must be the only field in the output
     *
     * @type {string}
     * @memberof GithubComSatstreamSsApiServerApiTransactionRequestsCreatePSBTOutput
     */
    data?: string;
}
