/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsUtilsBitcoinCliBip32Deriv
 */
export interface GithubComSatstreamSsUtilsBitcoinCliBip32Deriv {

    /**
     * The fingerprint of the master key
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliBip32Deriv
     */
    masterFingerprint?: string;

    /**
     * The derivation path
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliBip32Deriv
     */
    path?: string;
}
