/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsUtilsBitcoinCliFeeRange
 */
export interface GithubComSatstreamSsUtilsBitcoinCliFeeRange {

    /**
     * End of feerate range
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliFeeRange
     */
    endrange?: number;

    /**
     * Current number of txs in mempool unconfirmed
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliFeeRange
     */
    inmempool?: number;

    /**
     * Number of txs that left mempool unconfirmed
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliFeeRange
     */
    leftmempool?: number;

    /**
     * Start of feerate range
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliFeeRange
     */
    startrange?: number;

    /**
     * Total number of txs confirmed
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliFeeRange
     */
    totalconfirmed?: number;

    /**
     * Number of txs confirmed within target
     *
     * @type {number}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliFeeRange
     */
    withintarget?: number;
}
