/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsBitcoinCliSegwitDetails } from './github-com-satstream-ss-utils-bitcoin-cli-segwit-details';
 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsUtilsBitcoinCliDecodedScript
 */
export interface GithubComSatstreamSsUtilsBitcoinCliDecodedScript {

    /**
     * The Bitcoin address (only if well-defined)
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliDecodedScript
     */
    address?: string;

    /**
     * Script public key
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliDecodedScript
     */
    asm?: string;

    /**
     * Inferred descriptor for the script
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliDecodedScript
     */
    desc?: string;

    /**
     * P2SH address wrapping this redeem script
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliDecodedScript
     */
    p2sh?: string;

    /**
     * Witness script details
     *
     * @type {GithubComSatstreamSsUtilsBitcoinCliSegwitDetails}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliDecodedScript
     */
    segwit?: GithubComSatstreamSsUtilsBitcoinCliSegwitDetails;

    /**
     * The output type
     *
     * @type {string}
     * @memberof GithubComSatstreamSsUtilsBitcoinCliDecodedScript
     */
    type?: string;
}
