/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsOrdServerResponsesDecodeResponse } from './github-com-satstream-ss-utils-ord-server-responses-decode-response';
 /**
 * 
 *
 * @export
 * @interface GithubComSatstreamSsApiServerApiTransactionResponsesDecodeResponse
 */
export interface GithubComSatstreamSsApiServerApiTransactionResponsesDecodeResponse {

    /**
     * @type {number}
     * @memberof GithubComSatstreamSsApiServerApiTransactionResponsesDecodeResponse
     */
    code?: number;

    /**
     * @type {GithubComSatstreamSsUtilsOrdServerResponsesDecodeResponse}
     * @memberof GithubComSatstreamSsApiServerApiTransactionResponsesDecodeResponse
     */
    data?: GithubComSatstreamSsUtilsOrdServerResponsesDecodeResponse;

    /**
     * @type {string}
     * @memberof GithubComSatstreamSsApiServerApiTransactionResponsesDecodeResponse
     */
    msg?: string;
}
