/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DecodedScript } from './decoded-script';
import { UtilsResponseEnvelope } from './utils-response-envelope';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20032
 */
export interface InlineResponse20032 extends UtilsResponseEnvelope {

    /**
     * @type {DecodedScript}
     * @memberof InlineResponse20032
     */
    data?: DecodedScript;
}
