/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { StatusResponse } from './status-response';
import { UtilsResponseEnvelope } from './utils-response-envelope';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20033
 */
export interface InlineResponse20033 extends UtilsResponseEnvelope {

    /**
     * @type {StatusResponse}
     * @memberof InlineResponse20033
     */
    data?: StatusResponse;
}
