/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BlockchainInfo } from './blockchain-info';
import { UtilsResponseEnvelope } from './utils-response-envelope';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20010
 */
export interface InlineResponse20010 extends UtilsResponseEnvelope {

    /**
     * @type {BlockchainInfo}
     * @memberof InlineResponse20010
     */
    data?: BlockchainInfo;
}
