/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UtilsResponseEnvelope } from './utils-response-envelope';
import { ValidateAddressResult } from './validate-address-result';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2003
 */
export interface InlineResponse2003 extends UtilsResponseEnvelope {

    /**
     * @type {ValidateAddressResult}
     * @memberof InlineResponse2003
     */
    data?: ValidateAddressResult;
}
