/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BlockStats } from './block-stats';
import { UtilsResponseEnvelope } from './utils-response-envelope';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2008
 */
export interface InlineResponse2008 extends UtilsResponseEnvelope {

    /**
     * @type {BlockStats}
     * @memberof InlineResponse2008
     */
    data?: BlockStats;
}
