/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PSBTAnalysis } from './psbtanalysis';
import { UtilsResponseEnvelope } from './utils-response-envelope';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20026
 */
export interface InlineResponse20026 extends UtilsResponseEnvelope {

    /**
     * @type {PSBTAnalysis}
     * @memberof InlineResponse20026
     */
    data?: PSBTAnalysis;
}
