/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ChainTxStats } from './chain-tx-stats';
import { UtilsResponseEnvelope } from './utils-response-envelope';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20014
 */
export interface InlineResponse20014 extends UtilsResponseEnvelope {

    /**
     * @type {ChainTxStats}
     * @memberof InlineResponse20014
     */
    data?: ChainTxStats;
}
