/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SatoshiResponse } from './satoshi-response';
import { UtilsResponseEnvelope } from './utils-response-envelope';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20030
 */
export interface InlineResponse20030 extends UtilsResponseEnvelope {

    /**
     * @type {SatoshiResponse}
     * @memberof InlineResponse20030
     */
    data?: SatoshiResponse;
}
