/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface LatestInscriptionsResponse
 */
export interface LatestInscriptionsResponse {

    /**
     * @type {Array<string>}
     * @memberof LatestInscriptionsResponse
     */
    ids?: Array<string>;

    /**
     * @type {boolean}
     * @memberof LatestInscriptionsResponse
     */
    more?: boolean;

    /**
     * @type {number}
     * @memberof LatestInscriptionsResponse
     */
    pageIndex?: number;
}
