/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MempoolFees } from './mempool-fees';
 /**
 * 
 *
 * @export
 * @interface MempoolEntry
 */
export interface MempoolEntry {

    /**
     * Number of in-mempool ancestor transactions
     *
     * @type {number}
     * @memberof MempoolEntry
     */
    ancestorcount?: number;

    /**
     * Virtual size of in-mempool ancestors
     *
     * @type {number}
     * @memberof MempoolEntry
     */
    ancestorsize?: number;

    /**
     * Whether this transaction is replaceable
     *
     * @type {boolean}
     * @memberof MempoolEntry
     */
    bip125Replaceable?: boolean;

    /**
     * Parent transaction IDs
     *
     * @type {Array<string>}
     * @memberof MempoolEntry
     */
    depends?: Array<string>;

    /**
     * Number of in-mempool descendant transactions
     *
     * @type {number}
     * @memberof MempoolEntry
     */
    descendantcount?: number;

    /**
     * Virtual size of in-mempool descendants
     *
     * @type {number}
     * @memberof MempoolEntry
     */
    descendantsize?: number;

    /**
     * Fee information
     *
     * @type {MempoolFees}
     * @memberof MempoolEntry
     */
    fees?: MempoolFees;

    /**
     * Block height when transaction entered pool
     *
     * @type {number}
     * @memberof MempoolEntry
     */
    height?: number;

    /**
     * Child transaction IDs
     *
     * @type {Array<string>}
     * @memberof MempoolEntry
     */
    spentby?: Array<string>;

    /**
     * Time transaction entered pool
     *
     * @type {number}
     * @memberof MempoolEntry
     */
    time?: number;

    /**
     * Whether this transaction is currently unbroadcast
     *
     * @type {boolean}
     * @memberof MempoolEntry
     */
    unbroadcast?: boolean;

    /**
     * Virtual transaction size
     *
     * @type {number}
     * @memberof MempoolEntry
     */
    vsize?: number;

    /**
     * Transaction weight
     *
     * @type {number}
     * @memberof MempoolEntry
     */
    weight?: number;

    /**
     * Hash of serialized transaction with witness data
     *
     * @type {string}
     * @memberof MempoolEntry
     */
    wtxid?: string;
}
