/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Script } from './script';
 /**
 * 
 *
 * @export
 * @interface PSBTWitnessUtxo
 */
export interface PSBTWitnessUtxo {

    /**
     * The value in BTC
     *
     * @type {number}
     * @memberof PSBTWitnessUtxo
     */
    amount?: number;

    /**
     * The script pub key
     *
     * @type {Script}
     * @memberof PSBTWitnessUtxo
     */
    scriptPubKey?: Script;
}
