/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FeeHorizonEstimate } from './fee-horizon-estimate';
 /**
 * 
 *
 * @export
 * @interface RawFeeEstimate
 */
export interface RawFeeEstimate {

    /**
     * Estimate for long time horizon
     *
     * @type {FeeHorizonEstimate}
     * @memberof RawFeeEstimate
     */
    _long?: FeeHorizonEstimate;

    /**
     * Estimate for medium time horizon
     *
     * @type {FeeHorizonEstimate}
     * @memberof RawFeeEstimate
     */
    medium?: FeeHorizonEstimate;

    /**
     * Estimate for short time horizon
     *
     * @type {FeeHorizonEstimate}
     * @memberof RawFeeEstimate
     */
    _short?: FeeHorizonEstimate;
}
