/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RequestsEstimateSmartFeeRequest
 */
export interface RequestsEstimateSmartFeeRequest {

    /**
     * Required: Confirmation target in blocks (1 - 1008)
     *
     * @type {number}
     * @memberof RequestsEstimateSmartFeeRequest
     */
    confTarget?: number;

    /**
     * Optional: The fee estimate mode (unset, economical, conservative)
     *
     * @type {string}
     * @memberof RequestsEstimateSmartFeeRequest
     */
    estimateMode?: string;
}
