/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RequestsGetRawMempoolRequest
 */
export interface RequestsGetRawMempoolRequest {

    /**
     * Optional: If verbose=false, returns txids with mempool sequence number
     *
     * @type {boolean}
     * @memberof RequestsGetRawMempoolRequest
     */
    mempoolSequence?: boolean;

    /**
     * Optional: True for detailed information, false for just txids
     *
     * @type {boolean}
     * @memberof RequestsGetRawMempoolRequest
     */
    verbose?: boolean;
}
