/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RequestsConvertToPSBTRequest
 */
export interface RequestsConvertToPSBTRequest {

    /**
     * The hex string of a raw transaction
     *
     * @type {string}
     * @memberof RequestsConvertToPSBTRequest
     */
    hexstring: string;

    /**
     * Whether the transaction hex is a serialized witness transaction. If not provided, heuristic tests will be used in decoding. If true, only witness deserialization will be tried. If false, only non-witness deserialization will be tried. This boolean should reflect whether the transaction has inputs (e.g. fully valid, or on-chain transactions), if known by the caller. Optional, defaults to heuristic tests if not provided.
     *
     * @type {boolean}
     * @memberof RequestsConvertToPSBTRequest
     */
    isWitness?: boolean;

    /**
     * If true, any signatures in the input will be discarded and conversion will continue. If false, RPC will fail if any signatures are present. Optional, defaults to false if not provided.
     *
     * @type {boolean}
     * @memberof RequestsConvertToPSBTRequest
     */
    permitSigdata?: boolean;
}
