/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RequestsVerifyMessageRequest
 */
export interface RequestsVerifyMessageRequest {

    /**
     * The bitcoin address to use for the signature
     *
     * @type {string}
     * @memberof RequestsVerifyMessageRequest
     */
    address?: string;

    /**
     * The message that was signed
     *
     * @type {string}
     * @memberof RequestsVerifyMessageRequest
     */
    message?: string;

    /**
     * The signature provided by the signer in base 64 encoding
     *
     * @type {string}
     * @memberof RequestsVerifyMessageRequest
     */
    signature?: string;
}
