/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RequestsCreatePSBTInput
 */
export interface RequestsCreatePSBTInput {

    /**
     * The sequence number to use for the input
     *
     * @type {number}
     * @memberof RequestsCreatePSBTInput
     */
    sequence?: number;

    /**
     * The transaction id of the output to spend
     *
     * @type {string}
     * @memberof RequestsCreatePSBTInput
     */
    txid?: string;

    /**
     * The output index number (vout) of the output to spend
     *
     * @type {number}
     * @memberof RequestsCreatePSBTInput
     */
    vout?: number;
}
