/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RequestsCreatePSBTInput } from './requests-create-psbtinput';
import { RequestsCreatePSBTOutput } from './requests-create-psbtoutput';
 /**
 * 
 *
 * @export
 * @interface RequestsCreatePSBTRequest
 */
export interface RequestsCreatePSBTRequest {

    /**
     * The inputs for the transaction
     *
     * @type {Array<RequestsCreatePSBTInput>}
     * @memberof RequestsCreatePSBTRequest
     */
    inputs: Array<RequestsCreatePSBTInput>;

    /**
     * Raw locktime. Non-0 value also locktime-activates inputs
     *
     * @type {number}
     * @memberof RequestsCreatePSBTRequest
     */
    locktime?: number;

    /**
     * The outputs for the transaction (each address can only appear once)
     *
     * @type {Array<RequestsCreatePSBTOutput>}
     * @memberof RequestsCreatePSBTRequest
     */
    outputs: Array<RequestsCreatePSBTOutput>;

    /**
     * Marks this transaction as BIP125-replaceable
     *
     * @type {boolean}
     * @memberof RequestsCreatePSBTRequest
     */
    replaceable?: boolean;
}
