/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsBitcoinCliTxSpendingPrevoutInput } from './github-com-satstream-ss-utils-bitcoin-cli-tx-spending-prevout-input';
 /**
 * 
 *
 * @export
 * @interface RequestsGetTxSpendingPrevoutRequest
 */
export interface RequestsGetTxSpendingPrevoutRequest {

    /**
     * The transaction outputs to check
     *
     * @type {Array<GithubComSatstreamSsUtilsBitcoinCliTxSpendingPrevoutInput>}
     * @memberof RequestsGetTxSpendingPrevoutRequest
     */
    outputs?: Array<GithubComSatstreamSsUtilsBitcoinCliTxSpendingPrevoutInput>;
}
