/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RequestsJoinPSBTsRequest
 */
export interface RequestsJoinPSBTsRequest {

    /**
     * Array of base64-encoded PSBTs to join
     *
     * @type {Array<string>}
     * @memberof RequestsJoinPSBTsRequest
     */
    psbts?: Array<string>;
}
