/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RequestsGetTxOutSetInfoRequest
 */
export interface RequestsGetTxOutSetInfoRequest {

    /**
     * Block hash or height
     *
     * @type {any}
     * @memberof RequestsGetTxOutSetInfoRequest
     */
    hashOrHeight?: any;

    /**
     * Which UTXO set hash should be calculated
     *
     * @type {string}
     * @memberof RequestsGetTxOutSetInfoRequest
     */
    hashType?: string;

    /**
     * Whether to use coinstatsindex
     *
     * @type {boolean}
     * @memberof RequestsGetTxOutSetInfoRequest
     */
    useIndex?: boolean;
}
