/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsBitcoinCliSmartFeeEstimate } from './github-com-satstream-ss-utils-bitcoin-cli-smart-fee-estimate';
 /**
 * 
 *
 * @export
 * @interface ResponsesEstimateSmartFeeResponse
 */
export interface ResponsesEstimateSmartFeeResponse {

    /**
     * @type {number}
     * @memberof ResponsesEstimateSmartFeeResponse
     */
    code?: number;

    /**
     * Smart fee estimation data
     *
     * @type {GithubComSatstreamSsUtilsBitcoinCliSmartFeeEstimate}
     * @memberof ResponsesEstimateSmartFeeResponse
     */
    data?: GithubComSatstreamSsUtilsBitcoinCliSmartFeeEstimate;

    /**
     * @type {string}
     * @memberof ResponsesEstimateSmartFeeResponse
     */
    msg?: string;
}
