/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ResponsesVerifyMessageResponse
 */
export interface ResponsesVerifyMessageResponse {

    /**
     * @type {number}
     * @memberof ResponsesVerifyMessageResponse
     */
    code?: number;

    /**
     * Whether the signature is verified or not
     *
     * @type {boolean}
     * @memberof ResponsesVerifyMessageResponse
     */
    data?: boolean;

    /**
     * @type {string}
     * @memberof ResponsesVerifyMessageResponse
     */
    msg?: string;
}
