/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ResponsesGetAddressBalanceData } from './responses-get-address-balance-data';
 /**
 * 
 *
 * @export
 * @interface ResponsesGetAddressBalance
 */
export interface ResponsesGetAddressBalance {

    /**
     * @type {number}
     * @memberof ResponsesGetAddressBalance
     */
    code?: number;

    /**
     * @type {ResponsesGetAddressBalanceData}
     * @memberof ResponsesGetAddressBalance
     */
    data?: ResponsesGetAddressBalanceData;

    /**
     * @type {string}
     * @memberof ResponsesGetAddressBalance
     */
    msg?: string;
}
