/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse } from './github-com-satstream-ss-utils-ord-server-responses-output-response';
 /**
 * 
 *
 * @export
 * @interface ResponsesGetOutputByOutpointResponse
 */
export interface ResponsesGetOutputByOutpointResponse {

    /**
     * @type {number}
     * @memberof ResponsesGetOutputByOutpointResponse
     */
    code?: number;

    /**
     * @type {GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse}
     * @memberof ResponsesGetOutputByOutpointResponse
     */
    data?: GithubComSatstreamSsUtilsOrdServerResponsesOutputResponse;

    /**
     * @type {string}
     * @memberof ResponsesGetOutputByOutpointResponse
     */
    msg?: string;
}
