/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ResponsesRuneHolder
 */
export interface ResponsesRuneHolder {

    /**
     * @type {string}
     * @memberof ResponsesRuneHolder
     */
    address?: string;

    /**
     * @type {string}
     * @memberof ResponsesRuneHolder
     */
    balance?: string;
}
