/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BigInt } from './big-int';
 /**
 * 
 *
 * @export
 * @interface ResponsesNonInscriptionUTXO
 */
export interface ResponsesNonInscriptionUTXO {

    /**
     * @type {string}
     * @memberof ResponsesNonInscriptionUTXO
     */
    address?: string;

    /**
     * @type {number}
     * @memberof ResponsesNonInscriptionUTXO
     */
    codeType?: number;

    /**
     * @type {number}
     * @memberof ResponsesNonInscriptionUTXO
     */
    height?: number;

    /**
     * @type {number}
     * @memberof ResponsesNonInscriptionUTXO
     */
    idx?: number;

    /**
     * @type {boolean}
     * @memberof ResponsesNonInscriptionUTXO
     */
    isOpInRBF?: boolean;

    /**
     * @type {boolean}
     * @memberof ResponsesNonInscriptionUTXO
     */
    isSpent?: boolean;

    /**
     * @type {BigInt}
     * @memberof ResponsesNonInscriptionUTXO
     */
    satoshi?: BigInt;

    /**
     * @type {string}
     * @memberof ResponsesNonInscriptionUTXO
     */
    scriptPk?: string;

    /**
     * @type {string}
     * @memberof ResponsesNonInscriptionUTXO
     */
    scriptType?: string;

    /**
     * @type {string}
     * @memberof ResponsesNonInscriptionUTXO
     */
    txid?: string;

    /**
     * @type {number}
     * @memberof ResponsesNonInscriptionUTXO
     */
    vout?: number;
}
