/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsBitcoinCliDecodedPSBT } from './github-com-satstream-ss-utils-bitcoin-cli-decoded-psbt';
 /**
 * 
 *
 * @export
 * @interface ResponsesDecodePSBTResponse
 */
export interface ResponsesDecodePSBTResponse {

    /**
     * @type {number}
     * @memberof ResponsesDecodePSBTResponse
     */
    code?: number;

    /**
     * Decoded PSBT data
     *
     * @type {GithubComSatstreamSsUtilsBitcoinCliDecodedPSBT}
     * @memberof ResponsesDecodePSBTResponse
     */
    data?: GithubComSatstreamSsUtilsBitcoinCliDecodedPSBT;

    /**
     * @type {string}
     * @memberof ResponsesDecodePSBTResponse
     */
    msg?: string;
}
