/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsRpcBlock } from './github-com-satstream-ss-utils-rpc-block';
 /**
 * 
 *
 * @export
 * @interface ResponsesGetBlockInfo
 */
export interface ResponsesGetBlockInfo {

    /**
     * @type {number}
     * @memberof ResponsesGetBlockInfo
     */
    code?: number;

    /**
     * @type {GithubComSatstreamSsUtilsRpcBlock}
     * @memberof ResponsesGetBlockInfo
     */
    data?: GithubComSatstreamSsUtilsRpcBlock;

    /**
     * @type {string}
     * @memberof ResponsesGetBlockInfo
     */
    msg?: string;
}
