/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsBitcoinCliTxSpendingPrevoutResult } from './github-com-satstream-ss-utils-bitcoin-cli-tx-spending-prevout-result';
 /**
 * 
 *
 * @export
 * @interface ResponsesGetTxSpendingPrevoutResponse
 */
export interface ResponsesGetTxSpendingPrevoutResponse {

    /**
     * @type {number}
     * @memberof ResponsesGetTxSpendingPrevoutResponse
     */
    code?: number;

    /**
     * Spending status for each output
     *
     * @type {Array<GithubComSatstreamSsUtilsBitcoinCliTxSpendingPrevoutResult>}
     * @memberof ResponsesGetTxSpendingPrevoutResponse
     */
    data?: Array<GithubComSatstreamSsUtilsBitcoinCliTxSpendingPrevoutResult>;

    /**
     * @type {string}
     * @memberof ResponsesGetTxSpendingPrevoutResponse
     */
    msg?: string;
}
