/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BigInt } from './big-int';
 /**
 * 
 *
 * @export
 * @interface ResponsesGetTxInfoData
 */
export interface ResponsesGetTxInfoData {

    /**
     * @type {string}
     * @memberof ResponsesGetTxInfoData
     */
    blkid?: string;

    /**
     * @type {number}
     * @memberof ResponsesGetTxInfoData
     */
    height?: number;

    /**
     * @type {number}
     * @memberof ResponsesGetTxInfoData
     */
    idx?: number;

    /**
     * @type {BigInt}
     * @memberof ResponsesGetTxInfoData
     */
    inSatoshi?: BigInt;

    /**
     * @type {number}
     * @memberof ResponsesGetTxInfoData
     */
    locktime?: number;

    /**
     * @type {number}
     * @memberof ResponsesGetTxInfoData
     */
    nIn?: number;

    /**
     * @type {number}
     * @memberof ResponsesGetTxInfoData
     */
    nInInscription?: number;

    /**
     * @type {number}
     * @memberof ResponsesGetTxInfoData
     */
    nLostInscription?: number;

    /**
     * @type {number}
     * @memberof ResponsesGetTxInfoData
     */
    nNewInscription?: number;

    /**
     * @type {number}
     * @memberof ResponsesGetTxInfoData
     */
    nOut?: number;

    /**
     * @type {number}
     * @memberof ResponsesGetTxInfoData
     */
    nOutInscription?: number;

    /**
     * @type {BigInt}
     * @memberof ResponsesGetTxInfoData
     */
    outSatoshi?: BigInt;

    /**
     * @type {number}
     * @memberof ResponsesGetTxInfoData
     */
    size?: number;

    /**
     * @type {string}
     * @memberof ResponsesGetTxInfoData
     */
    txid?: string;
}
