/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsBitcoinCliDecodedScript } from './github-com-satstream-ss-utils-bitcoin-cli-decoded-script';
 /**
 * 
 *
 * @export
 * @interface ResponsesDecodeScriptResponse
 */
export interface ResponsesDecodeScriptResponse {

    /**
     * @type {number}
     * @memberof ResponsesDecodeScriptResponse
     */
    code?: number;

    /**
     * Decoded script data
     *
     * @type {GithubComSatstreamSsUtilsBitcoinCliDecodedScript}
     * @memberof ResponsesDecodeScriptResponse
     */
    data?: GithubComSatstreamSsUtilsBitcoinCliDecodedScript;

    /**
     * @type {string}
     * @memberof ResponsesDecodeScriptResponse
     */
    msg?: string;
}
