/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsBitcoinCliRawTx2 } from './github-com-satstream-ss-utils-bitcoin-cli-raw-tx2';
 /**
 * 
 *
 * @export
 * @interface ResponsesGetRawTransactionPrevoutResponse
 */
export interface ResponsesGetRawTransactionPrevoutResponse {

    /**
     * @type {number}
     * @memberof ResponsesGetRawTransactionPrevoutResponse
     */
    code?: number;

    /**
     * @type {GithubComSatstreamSsUtilsBitcoinCliRawTx2}
     * @memberof ResponsesGetRawTransactionPrevoutResponse
     */
    data?: GithubComSatstreamSsUtilsBitcoinCliRawTx2;

    /**
     * @type {string}
     * @memberof ResponsesGetRawTransactionPrevoutResponse
     */
    msg?: string;
}
