/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsBitcoinCliBlock2 } from './github-com-satstream-ss-utils-bitcoin-cli-block2';
 /**
 * 
 *
 * @export
 * @interface ResponsesGetBlockDecodedResponse
 */
export interface ResponsesGetBlockDecodedResponse {

    /**
     * @type {number}
     * @memberof ResponsesGetBlockDecodedResponse
     */
    code?: number;

    /**
     * @type {GithubComSatstreamSsUtilsBitcoinCliBlock2}
     * @memberof ResponsesGetBlockDecodedResponse
     */
    data?: GithubComSatstreamSsUtilsBitcoinCliBlock2;

    /**
     * @type {string}
     * @memberof ResponsesGetBlockDecodedResponse
     */
    msg?: string;
}
