/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ResponsesPaginationInfo } from './responses-pagination-info';
import { ResponsesRuneInfo } from './responses-rune-info';
 /**
 * 
 *
 * @export
 * @interface ResponsesGetRunesInfoListData
 */
export interface ResponsesGetRunesInfoListData {

    /**
     * @type {ResponsesPaginationInfo}
     * @memberof ResponsesGetRunesInfoListData
     */
    pagination?: ResponsesPaginationInfo;

    /**
     * @type {Array<ResponsesRuneInfo>}
     * @memberof ResponsesGetRunesInfoListData
     */
    runes?: Array<ResponsesRuneInfo>;
}
