/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsBitcoinCliMempoolInfo } from './github-com-satstream-ss-utils-bitcoin-cli-mempool-info';
 /**
 * 
 *
 * @export
 * @interface ResponsesGetMempoolInfoResponse
 */
export interface ResponsesGetMempoolInfoResponse {

    /**
     * @type {number}
     * @memberof ResponsesGetMempoolInfoResponse
     */
    code?: number;

    /**
     * Mempool information
     *
     * @type {GithubComSatstreamSsUtilsBitcoinCliMempoolInfo}
     * @memberof ResponsesGetMempoolInfoResponse
     */
    data?: GithubComSatstreamSsUtilsBitcoinCliMempoolInfo;

    /**
     * @type {string}
     * @memberof ResponsesGetMempoolInfoResponse
     */
    msg?: string;
}
