/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ResponsesGetAddressRunesBalanceListItem } from './responses-get-address-runes-balance-list-item';
 /**
 * 
 *
 * @export
 * @interface ResponsesGetAddressRunesBalanceListData
 */
export interface ResponsesGetAddressRunesBalanceListData {

    /**
     * @type {Array<ResponsesGetAddressRunesBalanceListItem>}
     * @memberof ResponsesGetAddressRunesBalanceListData
     */
    items?: Array<ResponsesGetAddressRunesBalanceListItem>;
}
