/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ResponsesSendRawTransactionData } from './responses-send-raw-transaction-data';
 /**
 * 
 *
 * @export
 * @interface ResponsesSendRawTransaction
 */
export interface ResponsesSendRawTransaction {

    /**
     * @type {number}
     * @memberof ResponsesSendRawTransaction
     */
    code?: number;

    /**
     * @type {ResponsesSendRawTransactionData}
     * @memberof ResponsesSendRawTransaction
     */
    data?: ResponsesSendRawTransactionData;

    /**
     * @type {string}
     * @memberof ResponsesSendRawTransaction
     */
    msg?: string;
}
