/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ResponsesGetFeesData } from './responses-get-fees-data';
 /**
 * 
 *
 * @export
 * @interface ResponsesGetFees
 */
export interface ResponsesGetFees {

    /**
     * @type {number}
     * @memberof ResponsesGetFees
     */
    code?: number;

    /**
     * @type {ResponsesGetFeesData}
     * @memberof ResponsesGetFees
     */
    data?: ResponsesGetFeesData;

    /**
     * @type {string}
     * @memberof ResponsesGetFees
     */
    msg?: string;
}
