/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsBitcoinCliEstimateRawFee } from './github-com-satstream-ss-utils-bitcoin-cli-estimate-raw-fee';
 /**
 * 
 *
 * @export
 * @interface ResponsesEstimateRawFeeResponse
 */
export interface ResponsesEstimateRawFeeResponse {

    /**
     * @type {number}
     * @memberof ResponsesEstimateRawFeeResponse
     */
    code?: number;

    /**
     * Fee estimation data
     *
     * @type {GithubComSatstreamSsUtilsBitcoinCliEstimateRawFee}
     * @memberof ResponsesEstimateRawFeeResponse
     */
    data?: GithubComSatstreamSsUtilsBitcoinCliEstimateRawFee;

    /**
     * @type {string}
     * @memberof ResponsesEstimateRawFeeResponse
     */
    msg?: string;
}
