/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ResponsesCreateRawTransactionResponse
 */
export interface ResponsesCreateRawTransactionResponse {

    /**
     * @type {number}
     * @memberof ResponsesCreateRawTransactionResponse
     */
    code?: number;

    /**
     * hex-encoded raw transaction
     *
     * @type {string}
     * @memberof ResponsesCreateRawTransactionResponse
     */
    data?: string;

    /**
     * @type {string}
     * @memberof ResponsesCreateRawTransactionResponse
     */
    msg?: string;
}
