/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsBitcoinCliChainTxStats } from './github-com-satstream-ss-utils-bitcoin-cli-chain-tx-stats';
 /**
 * 
 *
 * @export
 * @interface ResponsesGetChainTxStatsResponse
 */
export interface ResponsesGetChainTxStatsResponse {

    /**
     * @type {number}
     * @memberof ResponsesGetChainTxStatsResponse
     */
    code?: number;

    /**
     * Chain transaction statistics
     *
     * @type {GithubComSatstreamSsUtilsBitcoinCliChainTxStats}
     * @memberof ResponsesGetChainTxStatsResponse
     */
    data?: GithubComSatstreamSsUtilsBitcoinCliChainTxStats;

    /**
     * @type {string}
     * @memberof ResponsesGetChainTxStatsResponse
     */
    msg?: string;
}
