/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsBitcoinCliTxOut } from './github-com-satstream-ss-utils-bitcoin-cli-tx-out';
 /**
 * 
 *
 * @export
 * @interface ResponsesGetTxOutResponse
 */
export interface ResponsesGetTxOutResponse {

    /**
     * @type {number}
     * @memberof ResponsesGetTxOutResponse
     */
    code?: number;

    /**
     * Transaction output details (null if not found)
     *
     * @type {GithubComSatstreamSsUtilsBitcoinCliTxOut}
     * @memberof ResponsesGetTxOutResponse
     */
    data?: GithubComSatstreamSsUtilsBitcoinCliTxOut;

    /**
     * @type {string}
     * @memberof ResponsesGetTxOutResponse
     */
    msg?: string;
}
