/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ResponsesGetMempoolDescendantsResponse
 */
export interface ResponsesGetMempoolDescendantsResponse {

    /**
     * @type {number}
     * @memberof ResponsesGetMempoolDescendantsResponse
     */
    code?: number;

    /**
     * Either []string or map[string]MempoolEntry depending on verbose flag
     *
     * @type {any}
     * @memberof ResponsesGetMempoolDescendantsResponse
     */
    data?: any;

    /**
     * @type {string}
     * @memberof ResponsesGetMempoolDescendantsResponse
     */
    msg?: string;
}
