/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsRpcBtcTx } from './github-com-satstream-ss-utils-rpc-btc-tx';
 /**
 * 
 *
 * @export
 * @interface ResponsesGetMempoolTxInfo
 */
export interface ResponsesGetMempoolTxInfo {

    /**
     * @type {number}
     * @memberof ResponsesGetMempoolTxInfo
     */
    code?: number;

    /**
     * @type {GithubComSatstreamSsUtilsRpcBtcTx}
     * @memberof ResponsesGetMempoolTxInfo
     */
    data?: GithubComSatstreamSsUtilsRpcBtcTx;

    /**
     * @type {string}
     * @memberof ResponsesGetMempoolTxInfo
     */
    msg?: string;
}
