/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ResponsesGetFeesData
 */
export interface ResponsesGetFeesData {

    /**
     * @type {number}
     * @memberof ResponsesGetFeesData
     */
    confirmationBlocks?: number;

    /**
     * @type {number}
     * @memberof ResponsesGetFeesData
     */
    feeRateInBtc?: number;
}
