/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ResponsesGetAddressTimeframeBalanceData } from './responses-get-address-timeframe-balance-data';
 /**
 * 
 *
 * @export
 * @interface ResponsesGetAddressTimeframeBalance
 */
export interface ResponsesGetAddressTimeframeBalance {

    /**
     * @type {number}
     * @memberof ResponsesGetAddressTimeframeBalance
     */
    code?: number;

    /**
     * @type {ResponsesGetAddressTimeframeBalanceData}
     * @memberof ResponsesGetAddressTimeframeBalance
     */
    data?: ResponsesGetAddressTimeframeBalanceData;

    /**
     * @type {string}
     * @memberof ResponsesGetAddressTimeframeBalance
     */
    msg?: string;
}
