/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GithubComSatstreamSsUtilsBitcoinCliValidateAddressResult } from './github-com-satstream-ss-utils-bitcoin-cli-validate-address-result';
 /**
 * 
 *
 * @export
 * @interface ResponsesValidateAddressResponse
 */
export interface ResponsesValidateAddressResponse {

    /**
     * @type {number}
     * @memberof ResponsesValidateAddressResponse
     */
    code?: number;

    /**
     * Address validation result
     *
     * @type {GithubComSatstreamSsUtilsBitcoinCliValidateAddressResult}
     * @memberof ResponsesValidateAddressResponse
     */
    data?: GithubComSatstreamSsUtilsBitcoinCliValidateAddressResult;

    /**
     * @type {string}
     * @memberof ResponsesValidateAddressResponse
     */
    msg?: string;
}
