/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RuneTerms } from './rune-terms';
 /**
 * 
 *
 * @export
 * @interface RuneEntry
 */
export interface RuneEntry {

    /**
     * @type {number}
     * @memberof RuneEntry
     */
    block?: number;

    /**
     * @type {number}
     * @memberof RuneEntry
     */
    burned?: number;

    /**
     * @type {number}
     * @memberof RuneEntry
     */
    divisibility?: number;

    /**
     * @type {string}
     * @memberof RuneEntry
     */
    etching?: string;

    /**
     * @type {number}
     * @memberof RuneEntry
     */
    mints?: number;

    /**
     * @type {number}
     * @memberof RuneEntry
     */
    number?: number;

    /**
     * @type {number}
     * @memberof RuneEntry
     */
    premine?: number;

    /**
     * @type {string}
     * @memberof RuneEntry
     */
    spacedRune?: string;

    /**
     * @type {string}
     * @memberof RuneEntry
     */
    symbol?: string;

    /**
     * @type {RuneTerms}
     * @memberof RuneEntry
     */
    terms?: RuneTerms;

    /**
     * @type {number}
     * @memberof RuneEntry
     */
    timestamp?: number;

    /**
     * @type {boolean}
     * @memberof RuneEntry
     */
    turbo?: boolean;
}
