/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RuneEntry } from './rune-entry';
 /**
 * 
 *
 * @export
 * @interface RuneResponse
 */
export interface RuneResponse {

    /**
     * @type {RuneEntry}
     * @memberof RuneResponse
     */
    entry?: RuneEntry;

    /**
     * @type {string}
     * @memberof RuneResponse
     */
    id?: string;

    /**
     * @type {boolean}
     * @memberof RuneResponse
     */
    mintable?: boolean;

    /**
     * @type {string}
     * @memberof RuneResponse
     */
    parent?: string;
}
