/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RuneListEntry } from './rune-list-entry';
 /**
 * 
 *
 * @export
 * @interface RunesListResponse
 */
export interface RunesListResponse {

    /**
     * @type {Array<RuneListEntry>}
     * @memberof RunesListResponse
     */
    entries?: Array<RuneListEntry>;

    /**
     * @type {boolean}
     * @memberof RunesListResponse
     */
    more?: boolean;

    /**
     * @type {number}
     * @memberof RunesListResponse
     */
    next?: number;

    /**
     * @type {number}
     * @memberof RunesListResponse
     */
    prev?: number;
}
