/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Duration } from './duration';
 /**
 * 
 *
 * @export
 * @interface StatusResponse
 */
export interface StatusResponse {

    /**
     * @type {boolean}
     * @memberof StatusResponse
     */
    addressIndex?: boolean;

    /**
     * @type {number}
     * @memberof StatusResponse
     */
    blessedInscriptions?: number;

    /**
     * @type {string}
     * @memberof StatusResponse
     */
    chain?: string;

    /**
     * @type {number}
     * @memberof StatusResponse
     */
    cursedInscriptions?: number;

    /**
     * @type {number}
     * @memberof StatusResponse
     */
    height?: number;

    /**
     * @type {Duration}
     * @memberof StatusResponse
     */
    initialSyncTime?: Duration;

    /**
     * @type {number}
     * @memberof StatusResponse
     */
    inscriptions?: number;

    /**
     * @type {number}
     * @memberof StatusResponse
     */
    lostSats?: number;

    /**
     * @type {string}
     * @memberof StatusResponse
     */
    minimumRuneForNextBlock?: string;

    /**
     * @type {boolean}
     * @memberof StatusResponse
     */
    runeIndex?: boolean;

    /**
     * @type {number}
     * @memberof StatusResponse
     */
    runes?: number;

    /**
     * @type {boolean}
     * @memberof StatusResponse
     */
    satIndex?: boolean;

    /**
     * @type {string}
     * @memberof StatusResponse
     */
    started?: string;

    /**
     * @type {boolean}
     * @memberof StatusResponse
     */
    transactionIndex?: boolean;

    /**
     * @type {boolean}
     * @memberof StatusResponse
     */
    unrecoverablyReorged?: boolean;

    /**
     * @type {Duration}
     * @memberof StatusResponse
     */
    uptime?: Duration;
}
