/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TestMempoolAcceptResult } from './test-mempool-accept-result';
 /**
 * 
 *
 * @export
 * @interface TestMempoolAcceptResponse
 */
export interface TestMempoolAcceptResponse {

    /**
     * @type {number}
     * @memberof TestMempoolAcceptResponse
     */
    code?: number;

    /**
     * @type {Array<TestMempoolAcceptResult>}
     * @memberof TestMempoolAcceptResponse
     */
    data?: Array<TestMempoolAcceptResult>;

    /**
     * @type {string}
     * @memberof TestMempoolAcceptResponse
     */
    msg?: string;
}
