/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TransactionInput } from './transaction-input';
import { TransactionOutput } from './transaction-output';
 /**
 * 
 *
 * @export
 * @interface TransactionDetails
 */
export interface TransactionDetails {

    /**
     * @type {Array<TransactionInput>}
     * @memberof TransactionDetails
     */
    input?: Array<TransactionInput>;

    /**
     * @type {number}
     * @memberof TransactionDetails
     */
    lockTime?: number;

    /**
     * @type {Array<TransactionOutput>}
     * @memberof TransactionDetails
     */
    output?: Array<TransactionOutput>;

    /**
     * @type {number}
     * @memberof TransactionDetails
     */
    version?: number;
}
