/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TransactionCreateRawTxInput } from './transaction-create-raw-tx-input';
 /**
 * 
 *
 * @export
 * @interface TransactionCreateRawTxRequest
 */
export interface TransactionCreateRawTxRequest {

    /**
     * The inputs for the transaction
     *
     * @type {Array<TransactionCreateRawTxInput>}
     * @memberof TransactionCreateRawTxRequest
     */
    inputs: Array<TransactionCreateRawTxInput>;

    /**
     * Raw locktime. Non-0 value also locktime-activates inputs Optional, defaults to 0
     *
     * @type {number}
     * @memberof TransactionCreateRawTxRequest
     */
    locktime?: number;

    /**
     * The outputs for the transaction Each address can only appear once and there can only be one 'data' object
     *
     * @type {Array<{ [key: string]: number; }>}
     * @memberof TransactionCreateRawTxRequest
     */
    outputs: Array<{ [key: string]: number; }>;

    /**
     * Marks this transaction as BIP125-replaceable Allows this transaction to be replaced by a transaction with higher fees If provided, it is an error if explicit sequence numbers are incompatible Optional, defaults to true
     *
     * @type {boolean}
     * @memberof TransactionCreateRawTxRequest
     */
    replaceable?: boolean;
}
