/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Input } from './input';
import { Output } from './output';
 /**
 * 
 *
 * @export
 * @interface Transaction
 */
export interface Transaction {

    /**
     * @type {Array<Input>}
     * @memberof Transaction
     */
    input?: Array<Input>;

    /**
     * @type {number}
     * @memberof Transaction
     */
    lockTime?: number;

    /**
     * @type {Array<Output>}
     * @memberof Transaction
     */
    output?: Array<Output>;

    /**
     * @type {number}
     * @memberof Transaction
     */
    version?: number;
}
