/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TransactionGetTxOutRequest
 */
export interface TransactionGetTxOutRequest {

    /**
     * Optional: Whether to include the mempool (default=true)
     *
     * @type {boolean}
     * @memberof TransactionGetTxOutRequest
     */
    includeMempool?: boolean;

    /**
     * Required: The transaction id
     *
     * @type {string}
     * @memberof TransactionGetTxOutRequest
     */
    txid?: string;

    /**
     * Required: vout number
     *
     * @type {number}
     * @memberof TransactionGetTxOutRequest
     */
    vout?: number;
}
