/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TransactionGetTxOutProofRequest
 */
export interface TransactionGetTxOutProofRequest {

    /**
     * Optional: If specified, looks for txid in the block with this hash
     *
     * @type {string}
     * @memberof TransactionGetTxOutProofRequest
     */
    blockhash?: string;

    /**
     * Required: Array of transaction ids to filter
     *
     * @type {Array<string>}
     * @memberof TransactionGetTxOutProofRequest
     */
    txids?: Array<string>;
}
