/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TxSpendingPrevoutInput
 */
export interface TxSpendingPrevoutInput {

    /**
     * The transaction id
     *
     * @type {string}
     * @memberof TxSpendingPrevoutInput
     */
    txid?: string;

    /**
     * The output number
     *
     * @type {number}
     * @memberof TxSpendingPrevoutInput
     */
    vout?: number;
}
