/* tslint:disable */
/* eslint-disable */
/**
 * Satstream API
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ScriptPubKey } from './script-pub-key';
 /**
 * 
 *
 * @export
 * @interface Vout
 */
export interface Vout {

    /**
     * @type {number}
     * @memberof Vout
     */
    n?: number;

    /**
     * @type {ScriptPubKey}
     * @memberof Vout
     */
    scriptPubKey?: ScriptPubKey;

    /**
     * @type {number}
     * @memberof Vout
     */
    value?: number;
}
